CODE_OF_CONDUCT.md, CONTRIBUTING.md, docs/policies/commits.md
Adiciona código de conduta
Adiciona documento de contribuição
Melhora política de commits
=> Padroniza o repositório em vista software livre

docs/policies/pull_request.md, docs/sprints/Abertura-Sprint-1.md, docs/sprints/Fechamento-Sprint-0.md
Adiciona-se os documentos de abertura da sprint 1 e fechamento da sprint 0. Além disso, muda-se a politica de pull request do projeto.
=> Abertura da Sprint 1 e Fechamento da Sprint 0

docs/metodologia.md
Adiciona o documento da metodologia aplica ao projeto, de maneira a manter a transparência dos processos e rituais aplicados pela equipe.
[Issue 28](https://github.com/fga-eps-mds/2018.2-Lino/issues/28)
=> Documento de Metodologia

docs/sprints/Abertura-Sprint-2.md
Adiciona o termo de abertura da Sprint 2. Decidindo todo trabalho que será executado e por quem.
=> Adiciona a abertura da Sprint 2

docs/policies/commits.md
Corrige o exemplo prático proposto na política de commits, onde não condiz com o explicado anteriormente. 
Issue #6.
=> Correção na política de commits

docs/documento-de-arquitetura.md
Refatora e evolui o previamente criado documento de arquitetura, atualizando informações referentes ao escopo e à arquitetura do projeto
#48
=> [WIP] Refatoração do Documento de Arquitetura

docs/abertura/canvas.md
Adiciona o modelo adaptado do Canvas como uma ferramenta de planejamento estratégico, que permitiu um melhor esboço do modelo de negócio do projeto.
#62
=> Adiciona arquivo do Canvas

docs/roadmap.md
Acrescenta roadmap para explicitar mapeamento de como será o produto a cada período de evolução, visando uma construção integral do produto.
#63
=> Adiciona primeira versão do Roadmap

rasa/Makefile, rasa/credentials.yml, rasa/data/nlu.md, rasa/data/stories.md, rasa/domain.yml, rasa/instructions.md, rasa/nlu_config.yml
Cria um bot simples com Rasa e estabelece uma conexão com o mensageiro Telegram para realizar as interações.
#50
=> Conecta o Rasa ao Telegram

docs/eap.md
Acrescenta documento de estrutura analítica de projeto.
#33
=> Adds first version of analytical structure of the project

docs/_config.yml, docs/termo-de-abertura.md
O Termo de Abertura fomaliza o inicio do projeto, onde se descrevem informações relacionadas ao projeto de forma que qualquer pessoas possa entender as principais particularidades deste.
Issue #31.
=> Termo de Abertura

docs/Backlog-do-produto.md
Acrescenta o backlog do produto. O artefato diz respeito à todo o trabalho que precisará ser realizado para chegarmos ao produto final.
#32
=> [WIP] Backlog do Produto

docs/sprints/Fechamento-Sprint-2.md
Documento referente funcionamento da Sprint 1 e a análise dessa
#40
=> Fechamento da Sprint 2

docs/sprints/Abertura-Sprint-4.md
Mostra debitos tecnicos da Sprint 3 e as novas issues a serem resolvidas
#20
=> Adiciona a Abertura de Sprint 4

docs/sprints/Fechamento-Sprint-3.md
Adiciona Fechamento da Sprint 3
=> Fechamento da Sprint 3

docs/sprints/Fechamento-Sprint-4.md
Adiciona o fechamento da Sprint 4.
=> [Issue_40] Adds Fechamento-Sprint-4.md

cron.requirements.txt, cronjob.Dockerfile, rasa/actions/notifications.py, rasa/crontab, rasa/data/intents/nlu.md, rasa/data/stories/stories.md, rasa/domain.yml, rasa/notifier.py, rasa/notify.sh, req.txt
Cria um cronjob que roda o script de notificação todos os dias às 7am
#104
=> Cria cronjob das notificações

Telegram.Dockerfile, cronjob.Dockerfile, docker-compose.yml, rasa/actions/notifications.py, rasa/crontab, rasa/data/intents/nlu.md, rasa/data/stories/stories.md, rasa/domain.yml, rasa/notification_config.py, rasa/notifier.py, req.txt, requirements.txt
Cria uma action que registra o usuário no banco de dados, e uma action que salva o id do usuário em uma lista para o envio de notificações
#103
=> Registra usuário no banco de dados

.gitlab-ci.yml, docker/Messenger.Dockerfile, rasa/actions/menu.py, rasa/actions/notifications.py, rasa/domain.yml, rasa/fb_credentials.py, rasa/notifier.py, rasa/train-messenger.py, rasa/train.py
Criar pipeline para deploy de produção e de homologação
#95
=> Criar pipeline para deploy

docs/Backlog-do-produto.md
Neste pr, adiciona-se uma tabela de tasks, onde algumas US ficam mais refinadas e melhor descritas.
=> Refinamento de US

Dockerfile, README.md, docker-compose.yml, docker/Messenger.Dockerfile, docker/Telegram.Dockerfile, rasa/actions/menu.py, rasa/actions/notifications.py, rasa/domain.yml, rasa/notifier.py, rasa/train-telegram.py, rasa/train.py
Havia um problema com o ambiente de desenvolvimento que tinha que mudar muitas variáveis para que se pudesse trocar o teste do bot para o terminal e para incluir para os mensageiros.
#120
=> Melhora o ambiente de desenvolvimento

.gitlab-ci.yml, rasa/actions/menu.py, rasa/actions/notifications.py, rasa/notification_config.py, rasa/notifier.py, rasa/train-messenger.py, rasa/train-telegram.py, rasa/train.py
Por falta de gerenciamento, códigos foram aceitos mesmo sem estar passando no stage de teste do flake8. Assim, esse PR refatora os erros aceitos anteriormentes no código.
Foi refatorado também o código para que fosse utilizado o interpretador correto, fazendo com que o Lino classifique corretamente as intents
#125
=> Refatora código para passar no flake8

docker-compose.yml, rasa/actions/notifications/register_notification.py, rasa/actions/notifications/start.py
Troca as uris dos bancos de dados para uma variável de ambiente
=> Adiciona variáveis de ambiente pro banco de dados

docker-compose.yml, rasa/actions/calendar.py, rasa/actions/notifications/register_notification.py, rasa/actions/notifications/start.py
Adiciona as variáveis de ambiente necessárias pro banco de dados.
=> Adiciona variáveis de ambiente

docker/Cronjob.Dockerfile, rasa/scripts/entrypoint_cron.sh
Altera o dockerfile do cronjob para rodar um script que salva as variáveis de ambiente em um arquivo e roda o cron.
=> Altera dockerfile do cronjob

docker/Cronjob.Dockerfile, rasa/crontab, rasa/scripts/env_loader.py, rasa/scripts/lunch_notifier.py, rasa/scripts/notify_lunch.sh
Cria um script de envio da notificação do almoço para os usuários cadastrados no banco de dados, e faz um agendamento para o envio da notificação às 10:30.
#172
=> Cria o script de envio do almoço

docker/Cronjob.Dockerfile, rasa/crontab, rasa/scripts/dinner_notifier.py, rasa/scripts/notify_dinner_meal.sh
Cria um script de envio do jantar para os usuários cadastrados no banco.
E agenda o envio de notificações às 17h
#173
=> Cria script de envio do Jantar

rasa/actions/menu/daily_breakfast.py, rasa/actions/menu/daily_dinner.py, rasa/actions/menu/daily_lunch.py, rasa/actions/menu/daily_menu.py, rasa/domain.yml
Foi arrumado os problemas das custom actions em relação a solicitação do cardápio do RU no fim de semana, tendo a capacidade de tratar as exceções e enviar uma mensagem de aviso, caso o usuário solicite no fim de semana.
#184
=> Arruma problemas das custom actions dos menus

rasa/data/intents/documents.md, rasa/data/stories/main.md, rasa/domain.yml
Este PR tem o objetivo de arrumar algumas linhas de código que impediam o reconhecimento do fluxo de documentos pelo Lino, de maneira que as intents estejam bem identificadas e escritas no domain.yml, documents.md e main.md.
#222
=> Refatoração do fluxo de conversa dos documentos

rasa/data/intents/offenses.md, rasa/data/stories/main.md, rasa/domain.yml
Trata as ofensas realizadas pelos usuários e endereçadas ao lino.
#198
=> [WIP] Cria fluxo para tratar ofensas

rasa/actions/menu/week_menu.py, rasa/actions/notifications/buttons_notification.py, rasa/actions/notifications/register_notification.py, rasa/actions/notifications/start.py, rasa/data/stories/main.md, rasa/domain.yml
O Lino até então não possuía uma padronização de suas falas. Isso, por sua vez, deixava o usuário as vezes um pouco confuso e pouco esclarecido. Esse PR visa concertar todos estes problemas de falta de padronização.
#221
=> Padroniza todas as utters para dialogo mais adequado do Lino com o usuário

docs/gitflow.md
Cria o documento responsável por elucidar o funcionamento da integração contínua de todos os serviços componentes do Lino.
* Visão Geral
* Descrição sobre todas as ferramentas utilizadas
* Descrição sobre todos os estágios do CI/CD
#236 
Ressalvas específicas sobre o PR
Foi criado o documento do Gitflow/DevOps. Agora as pessoas já estão hábeis para saber como/o que utilizamos para resolver nossos problemas de automação da entrega contínua.
=> Cria documento de DevOps/Gitflow

rasa/data/intents/general.md, rasa/data/intents/menu.md, rasa/data/intents/notifications.md, rasa/data/intents/random.md, rasa/data/stories/main.md, rasa/domain.yml
Este PR tem como objetivo aumentar a quantidade de fluxos do bot, para que ele tenha maior usabilidade e que o diálogo seja mais agradável
#243
=> Adiciona fluxos para inclusão de melhor usabilidade
